image: nsumner/cmpt373:projectbase

stages:
  - build
  - test
  - analyze

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=True ../
    - make
  artifacts:
    expire_in: 10 mins
    paths:
      - build/*

test:
  stage: test
  script:
    - build/bin/runAllTests

analyze:
  stage: analyze
  script:
    - cppcheck lib/* 2> build/cppcheck-results.txt
    - cd build
    - >-
     /usr/lib/llvm-6.0/share/clang/run-clang-tidy.py
     -checks='*,-fuchsia-*,-google-readability-todo,-llvm-*,
     -google-runtime-references,-misc-unused-parameters,
     -google-readability-namespace-comments,
     -readability-else-after-return' '^(?!.*(googletest|test|networking|nlohmann)).*' > clang-tidy-results.txt
  artifacts:
    expire_in: 1 hour
    paths:
      - build/cppcheck-results.txt
      - build/clang-tidy-results.txt