image: nsumner/cmpt373:projectbase

stages:
  - build
  - analyze
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=True ../
    - make
  artifacts:
    expire_in: 30 mins
    paths:
      - build/*

build-release:
  stage: build
  script:
    - mkdir build-release
    - cd build-release
    - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=clang++ ../
    - make
  artifacts:
    expire_in: 5 mins
    paths:
      - build/*
  allow_failure: true
  only:
    - master

analyze:
  stage: analyze
  script:
    - cppcheck lib/* 2> build/cppcheck-results.txt
    - cd build
    - >-
     /usr/lib/llvm-6.0/share/clang/run-clang-tidy.py
     -checks='*,-fuchsia-*,-google-readability-todo,-llvm-*,
     -google-runtime-references,-misc-unused-parameters,
     -google-readability-namespace-comments,
     -readability-else-after-return' '^(?!.*(googletest|test|networking|nlohmann)).*' > clang-tidy-results.txt
  artifacts:
    expire_in: 1 hour
    paths:
      - build/cppcheck-results.txt
      - build/clang-tidy-results.txt
  except:
    - docs

headerdoc2html:
  stage: analyze
  script:
    - echo '...Debugging...'
    - ls
    - cd bin/
    - ls
    - cd ../../
    - ls
  allow_failure: true
  only:
    - docs
    
gatherheaderdoc:
  stage: analyze
  script:
    - find . -regex '.*\.h'
    - find lib -regex '.*\.h'
    - sh bin/headerdoc2html doc/.HeaderDoc/ $(find lib -regex '.*\.h')
  allow_failure: true
  only:
    - docs

test:
  stage: test
  script:
    - build/bin/runAllTests
